// Web/roomkit/vue3/RoomKit/components/ParticipantButton/MemberRegistrar.vue
<script setup lang="ts">
import { onUnmounted } from 'vue';
import { useUIKit } from '@tencentcloud/uikit-base-component-vue3';
import { RoomParticipantList, useRoomState } from 'tuikit-atomicx-vue3/room';
import { conference } from '../../adapter/conference';
import { BuiltinWidget } from '../../adapter/type';
import ParticipantButton from './index.vue';

const { t } = useUIKit();
const { currentRoom } = useRoomState();

const unregister = conference.registerWidget({
  id: BuiltinWidget.MemberWidget,
  zone: { pc: 'bottom-center' },
  order: 4,
  component: ParticipantButton,
  panel: {
    title: () => t('Participant.Title', { count: currentRoom.value?.participantCount }),
    component: RoomParticipantList,
  },
});

onUnmounted(() => unregister());
</script>

<template>
  <!-- Registrar: registration-only, rendering handled by CustomWidgetRenderer -->
</template>

// Web/roomkit/react/RoomKit/components/MemberButton/MemberRegistrar.tsx
import { useEffect } from 'react';
import { useUIKit } from '@tencentcloud/uikit-base-component-react';
import { RoomParticipantList } from 'tuikit-atomicx-react/room';
import { BuiltinWidget } from '../../adapter/type';
import { useRoomSidePanel } from '../../hooks/useRoomSidePanel';
import { MemberButton } from './MemberButton';

/**
 * Registration-only component: mounts the member list panel into the side
 * panel store. Mirrors Vue `MemberRegistrar.vue` (empty template, register on
 * mount). Renders the trigger button alongside.
 */
export function MemberRegistrar() {
  const { t } = useUIKit();
  const { registerSidePanel } = useRoomSidePanel();

  useEffect(
    () => registerSidePanel({
      id: BuiltinWidget.MemberWidget,
      title: () => t('Participant.Title'),
      render: () => <RoomParticipantList />,
    }),
    [registerSidePanel, t],
  );

  return <MemberButton />;
}
