// Web/roomkit/vue3/RoomKit/components/RoomChat/ChatButton.vue
<template>
  <IconButton :title="t('Chat.Title')" @click-icon="handleClick">
    <Badge :value="unreadCount" :hidden="!unreadCount">
      <IconChat :size="24" />
    </Badge>
  </IconButton>
</template>

<script setup lang="ts">
import { onUnmounted, ref, watch } from 'vue';
import {
  IconChat,
  useUIKit,
  Badge,
} from '@tencentcloud/uikit-base-component-vue3';
import { useConversationListState, useMessageListState } from 'tuikit-atomicx-vue3/chat';
import { useLoginState, useRoomState } from 'tuikit-atomicx-vue3/room';
import IconButton from '../base/IconButton.vue';

interface Props {
  isActive?: boolean;
  togglePanel?: () => void;
}

const props = withDefaults(defineProps<Props>(), {
  isActive: false,
  togglePanel: undefined,
});

const { t } = useUIKit();

const { setActiveConversation } = useConversationListState();
const { currentRoom } = useRoomState();
const { loginUserInfo } = useLoginState();
const { messageList } = useMessageListState();

const unreadCount = ref(0);
const hasInitializedMessageList = ref(false);

const resetUnreadTracking = () => {
  unreadCount.value = 0;
  hasInitializedMessageList.value = false;
};

watch(
  messageList,
  (newMessageList, oldMessageList) => {
    const currentMessageList = newMessageList || [];

    if (!hasInitializedMessageList.value) {
      hasInitializedMessageList.value = true;
      return;
    }

    if (props.isActive) {
      return;
    }

    const previousLength = oldMessageList?.length || 0;
    if (currentMessageList.length <= previousLength) {
      return;
    }

    const unreadMessages = currentMessageList
      .slice(previousLength)
      .filter(message => message?.from !== loginUserInfo.value?.userId);

    unreadCount.value += unreadMessages.length;
  },
  { deep: false },
);

watch(
  () => props.isActive,
  (isOpen) => {
    if (isOpen) {
      unreadCount.value = 0;
    }
  },
);

watch(
  () => currentRoom.value?.roomId,
  (roomId) => {
    resetUnreadTracking();
    if (!loginUserInfo.value?.userId) {
      return;
    }
    if (!roomId) {
      setActiveConversation('');
      return;
    }
    setActiveConversation(`GROUP${roomId}`);
  },
  { immediate: true },
);

onUnmounted(() => {
  setActiveConversation('');
});

const handleClick = () => {
  unreadCount.value = 0;
  props.togglePanel?.();
};
</script>

// Web/roomkit/react/RoomKit/components/RoomChat/ChatButton.tsx
import { useEffect, useRef, useState } from 'react';
import {
  TUIBadge,
  IconChat,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import {
  useChatContext,
} from 'tuikit-atomicx-react/chat';
import { useLoginState, useRoomState } from 'tuikit-atomicx-react/room';
import { BuiltinWidget } from '../../adapter/type';
import { useRoomSidePanel } from '../../hooks/useRoomSidePanel';
import { IconButton } from '../base/IconButton';

export function ChatButton() {
  const { t } = useUIKit();
  const { activeId, togglePanel } = useRoomSidePanel();
  const isActive = activeId === BuiltinWidget.RoomChatWidget;

  const { setActiveConversation, activeConversationID, messageListOnEvent } = useChatContext();
  const { currentRoom } = useRoomState();
  const { loginUserInfo } = useLoginState();

  const [unreadCount, setUnreadCount] = useState(0);
  const isActiveRef = useRef(isActive);

  useEffect(() => {
    isActiveRef.current = isActive;
  }, [isActive]);

  // Subscribe to new message events, mirrors MessageList.tsx messageListOnEvent usage.
  // Re-subscribe whenever the active conversation changes.
  useEffect(() => {
    if (!activeConversationID || !messageListOnEvent) {
      return undefined;
    }
    const unsub = messageListOnEvent((event) => {
      if (event.type !== 'onReceiveNewMessage') {
        return;
      }
      const { message } = event;
      if (message.isSentBySelf || isActiveRef.current) {
        return;
      }
      setUnreadCount(prev => prev + 1);
    });
    return unsub;
  }, [activeConversationID, messageListOnEvent]);

  // Clear unread count when the panel opens.
  useEffect(() => {
    if (isActive) {
      setUnreadCount(0);
    }
  }, [isActive]);

  // Bind / clear the active conversation as the room changes (mirrors Vue's
  // watch on currentRoom.roomId with `immediate: true`).
  useEffect(() => {
    const roomId = currentRoom?.roomId;
    setUnreadCount(0);
    if (!loginUserInfo?.userId) {
      return;
    }
    if (!roomId) {
      setActiveConversation('');
      return;
    }
    setActiveConversation(`GROUP${roomId}`);
  }, [currentRoom?.roomId, loginUserInfo?.userId, setActiveConversation]);

  // Clear the active conversation when the button unmounts.
  useEffect(
    () => () => {
      setActiveConversation('');
    },
    [setActiveConversation],
  );

  const handleClick = () => {
    setUnreadCount(0);
    togglePanel(BuiltinWidget.RoomChatWidget);
  };

  return (
    <IconButton title={t('Chat.Title')} onClickIcon={handleClick}>
      <TUIBadge value={unreadCount} hidden={!unreadCount}>
        <IconChat size="24" />
      </TUIBadge>
    </IconButton>
  );
}
