// Web/roomkit/vue3/RoomKit/components/CurrentRoomInfo/index.vue
<template>
  <div v-if="currentRoom?.roomId" class="room-header">
    <TUIDropdown
      trigger="click"
      placement="bottom"
      :hideOnClick="false"
      :teleported="false"
    >
      <div class="room-title">
        <span class="room-title-name">{{ currentRoom?.roomName || currentRoom?.roomId }}</span>
        <IconCaretDownSmall :size="24" class="room-title-icon" />
        <span class="room-duration">{{ durationTime }}</span>
      </div>
      <template #dropdown>
        <div class="room-info">
          <div class="room-info-item">
            <div class="room-info-label">
              {{ t('CurrentRoomInfo.Host') }}
            </div>
            <div class="room-info-value">
              {{ currentRoom?.roomOwner.userName || currentRoom?.roomOwner.userId }}
            </div>
          </div>
          <div class="room-info-item">
            <div class="room-info-label">
              {{ t('CurrentRoomInfo.RoomId') }}
            </div>
            <div class="room-info-value">
              {{ currentRoom?.roomId }}
            </div>
            <div class="room-info-copy" @click="() => copy(currentRoom?.roomId || '')">
              <IconCopy class="copy-icon" />
              <span>{{ t('CurrentRoomInfo.Copy') }}</span>
            </div>
          </div>
          <div v-if="currentRoom?.password" class="room-info-item">
            <div class="room-info-label">
              {{ t('CurrentRoomInfo.Password') }}
            </div>
            <div class="room-info-value">
              {{ currentRoom?.password }}
            </div>
            <div class="room-info-copy" @click="() => copy(currentRoom?.password || '')">
              <IconCopy class="copy-icon" />
              <span>{{ t('CurrentRoomInfo.Copy') }}</span>
            </div>
          </div>
          <div v-if="isRoomLinkVisible" class="room-info-item">
            <div class="room-info-label">
              {{ t('CurrentRoomInfo.RoomLink') }}
            </div>
            <div class="room-info-value">
              {{ roomLink }}
            </div>
            <div class="room-info-copy" @click="() => copy(roomLink)">
              <IconCopy class="copy-icon" />
              <span>{{ t('CurrentRoomInfo.Copy') }}</span>
            </div>
          </div>
        </div>
      </template>
    </TUIDropdown>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { TUIDropdown, IconCaretDownSmall, IconCopy, useUIKit } from '@tencentcloud/uikit-base-component-vue3';
import { useRoomState } from 'tuikit-atomicx-vue3/room';
import { conference } from '../../adapter/conference';
import { useCopy } from '../../hooks/useCopy';
import { generateRoomLink } from '../../utils/utils';

const { t } = useUIKit();
const { currentRoom } = useRoomState();
const { copy } = useCopy();

const currentTime = ref(Date.now());
let timer: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
  timer = setInterval(() => {
    currentTime.value = Date.now();
  }, 1000);
});

onUnmounted(() => {
  if (timer) {
    clearInterval(timer);
  }
});

const isRoomLinkVisible = computed(() => conference.getFeatureConfig('shareLink') !== '');

const roomLink = computed(() => {
  const customLink = conference.getFeatureConfig('shareLink');
  if (customLink === '') {
    return '';
  }
  if (customLink) {
    return customLink;
  }
  if (!currentRoom.value?.roomId) {
    return '';
  }
  return generateRoomLink(currentRoom.value.roomId, currentRoom.value.password, currentRoom.value.roomType);
});

const durationTime = computed(() => {
  if (!currentRoom.value?.roomId) {
    return '00:00';
  }

  const duration = currentTime.value - (currentRoom.value.createTime ?? 0);
  const totalSeconds = Math.floor(duration / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  if (hours > 0) {
    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  }

  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
});

</script>

<style lang="scss" scoped>
.room-title {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  gap: 8px;
  cursor: pointer;
  font-size: 18px;
  font-weight: 600;
  color: var(--text-color-primary);
  min-width: 0;

  .room-title-name {
    max-width: 300px;
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .room-title-icon {
    flex-shrink: 0;
  }

  .room-duration {
    font-size: 14px;
    font-weight: 500;
    line-height: 20px;
    text-align: center;
    flex-shrink: 0;
  }
}

.room-info {
  display: flex;
  flex-direction: column;
  padding: 20px;
  background-color: var(--bg-color-dialog);
  border-radius: 16px;
  gap: 12px;

  .room-info-item {
    display: flex;
    flex-direction: row;
    justify-content: flex-start;
    align-items: center;
    gap: 6px;
    font-size: 14px;

    .room-info-label {
      min-width: 80px;
      color: var(--text-color-secondary);
      font-size: 14px;
      line-height: 22px;
      flex-shrink: 0;
      text-align: start;
    }

    .room-info-value {
      flex: 1;
      color: var(--text-color-primary);
      font-size: 14px;
      line-height: 22px;
      gap: 8px;
      text-align: start;
      word-break: break-all;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      max-width: 200px;
    }
  }
}

.room-info-copy {
  display: flex;
  align-items: center;
  gap: 4px;
  color: var(--text-color-link);
  cursor: pointer;

  .copy-icon {
    flex-shrink: 0;

    &:hover {
      color: var(--text-color-link-hover);
    }
  }
}
</style>

// Web/roomkit/react/RoomKit/components/CurrentRoomInfo/CurrentRoomInfo.tsx
import { useEffect, useMemo, useState } from 'react';
import {
  IconCaretDownSmall,
  IconCopy,
  TUIDropdown,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import { useRoomState } from 'tuikit-atomicx-react/room';
import { conference as conferenceImpl } from '../../adapter/conference';
import { useCopy } from '../../hooks/useCopy';
import { generateRoomLink } from '../../utils/utils';
import styles from './CurrentRoomInfo.module.scss';
import type { IConference } from '../../adapter/type';

const conference = conferenceImpl as unknown as IConference;

function formatDurationTime(createTime: number | undefined, now: number) {
  if (!createTime) {
    return '00:00';
  }

  const totalSeconds = Math.floor((now - createTime) / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  if (hours > 0) {
    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  }

  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

/**
 * Conference header room title with duration and room detail dropdown.
 */
export function CurrentRoomInfo() {
  const { t } = useUIKit();
  const { currentRoom } = useRoomState();
  const { copy } = useCopy();
  const [currentTime, setCurrentTime] = useState(() => Date.now());

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(Date.now());
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const roomLink = useMemo(() => {
    const customLink = conference.getFeatureConfig('shareLink');
    if (customLink) {
      return customLink;
    }
    if (!currentRoom?.roomId) {
      return '';
    }
    return generateRoomLink(
      currentRoom.roomId,
      currentRoom.password,
      currentRoom.roomType,
    );
  }, [currentRoom?.roomId, currentRoom?.password, currentRoom?.roomType]);

  const durationTime = useMemo(
    () => formatDurationTime(currentRoom?.createTime, currentTime),
    [currentRoom?.createTime, currentTime],
  );

  if (!currentRoom?.roomId) {
    return null;
  }

  const roomTitle = currentRoom.roomName || currentRoom.roomId;
  const hostName = currentRoom.roomOwner?.userName || currentRoom.roomOwner?.userId || '';

  const dropdownContent = (
    <div className={styles.roomInfo}>
      <div className={styles.roomInfoItem}>
        <div className={styles.roomInfoLabel}>
          {t('CurrentRoomInfo.Host')}
        </div>
        <div className={styles.roomInfoValue}>{hostName}</div>
      </div>
      <div className={styles.roomInfoItem}>
        <div className={styles.roomInfoLabel}>
          {t('CurrentRoomInfo.RoomId')}
        </div>
        <div className={styles.roomInfoValue}>{currentRoom.roomId}</div>
        <div
          className={styles.roomInfoCopy}
          onClick={() => copy(currentRoom.roomId)}
        >
          <IconCopy className={styles.copyIcon} />
          <span>{t('CurrentRoomInfo.Copy')}</span>
        </div>
      </div>
      {currentRoom.password
        ? (
          <div className={styles.roomInfoItem}>
            <div className={styles.roomInfoLabel}>
              {t('CurrentRoomInfo.Password')}
            </div>
            <div className={styles.roomInfoValue}>{currentRoom.password}</div>
            <div
              className={styles.roomInfoCopy}
              onClick={() => copy(currentRoom.password ?? '')}
            >
              <IconCopy className={styles.copyIcon} />
              <span>{t('CurrentRoomInfo.Copy')}</span>
            </div>
          </div>
        )
        : null}
      <div className={styles.roomInfoItem}>
        <div className={styles.roomInfoLabel}>
          {t('CurrentRoomInfo.RoomLink')}
        </div>
        <div className={styles.roomInfoValue}>{roomLink}</div>
        <div
          className={styles.roomInfoCopy}
          onClick={() => copy(roomLink)}
        >
          <IconCopy className={styles.copyIcon} />
          <span>{t('CurrentRoomInfo.Copy')}</span>
        </div>
      </div>
    </div>
  );

  return (
    <div className={styles.roomHeader}>
      <TUIDropdown
        trigger="click"
        placement="bottom"
        hideOnClick={false}
        teleported={false}
        dropdownContent={dropdownContent}
      >
        <div className={styles.roomTitle}>
          <span className={styles.roomTitleName}>{roomTitle}</span>
          <IconCaretDownSmall size={24} className={styles.roomTitleIcon} />
          <span className={styles.roomDuration}>{durationTime}</span>
        </div>
      </TUIDropdown>
    </div>
  );
}
